services:
  postgres:
    build:
      context: ../Database
    container_name: eventflow_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../Database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../Database/cron.sql:/docker-entrypoint-initdb.d/cron.sql
    command: >
      postgres -c shared_preload_libraries=pg_cron
               -c cron.database_name=${DB_NAME}

  api:
    build: ../Backend
    container_name: eventflow_api
    restart: always
    ports:
      - "3003:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      NODE_ENV: production
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      - postgres

  frontend:
    build:
      context: ../Frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: eventflow_front
    restart: always
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - api

volumes:
  pgdata:
